/** 统一用户可见文案，避免各页各写一套 */
export const UI = {
  placeholder: {
    productName: '如 可乐 330ml',
    barcode: '商品条码',
    retailPrice: '如 3.5',
    friendPrice: '如 3.2',
    purchasePrice: '进货成本',
    saleUnit: '件 / 条 / 箱',
    versionName: '如 本地版',
    category: '如 饮料',
    brand: '如 可口可乐',
    alias: '如 快乐水',
    notes: '',
    customerName: '客户姓名',
    phone: '手机号',
    address: '详细地址',
    supplier: '如 城北批发部',
    orderNote: '备注',
    payNote: '备注',
    promoContent: '如 100 元 3 件',
    prizeDesc: '如 再来一瓶',
    prizeExtra: '加价元数，填 0 为免费',
  },
  label: {
    productName: '商品名称',
    barcode: '商品条码',
    retailPrice: '零售价（元）',
    friendPrice: '友情价',
    purchasePrice: '进货价（元）',
    saleUnit: '销售单位',
    versionName: '版本名',
    category: '分类',
    brand: '品牌',
    alias: '别名',
    notes: '备注',
    promotions: '优惠',
    prizes: '奖品',
  },
  helper: {
    alias: '多个别名用空格分开',
    scanFill: '扫码可自动带出名称和图片',
    notes: '仅自己可见',
  },
  example: {
    prize: '再来一瓶',
    prize2: '加 1 元换购',
    promo: '100 元 3 件',
  },
} as const
